Refactor 'brew install' code into a function

diff --git a/utilities b/utilities
--- a/utilities
+++ b/utilities
@@ -59,6 +59,29 @@ create_symlink() {
   return 1
 }
 
+brew_install() {
+  formula_readable_name="$1"
+  formula="$2"
+  tap_value="$3"
+
+  if [ -n "$tap_value" ]; then
+    if ! brew tap "$tap_value"; then
+      print_error "$formula ('brew tap $tap_value' failed)" && exit 1
+    fi
+  fi
+
+  if brew list "$formula" &> /dev/null; then
+    # Package is already installed.
+    print_success "$formula_readable_name"
+  else
+    # Install package.
+    brew install $formula
+    # Exit if installation fails.
+    [ $? -ne 0 ] && print_error "$formula_readable_name" && exit 1
+    print_success "$formula_readable_name"
+  fi
+}
+
 start_notice() {
 cat << EOF
 //////////////////////////////////////////////////////////////////
